<a href="https://colab.research.google.com/github/SIUTRITUE/Machine_Learning/blob/main/Tuan2_hocmay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài tập 1: Tạo và Cắt lát

Yêu Cầu:
• Tạo một vector chứa các số từ 1 đến 16.
• Sử dụng `reshape` để biến nó thành ma trận 4x4.
• Trích xuất ma trận 2x2 ở góc dưới bên phải (các phần tử 11,
12, 15, 16)

In [ ]:
import numpy as np
vector=np.arange(1,17)
matrix=vector.reshape(4, 4)
print(matrix)
bottom_right = matrix[2:,2:]
print(bottom_right)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[11 12]
 [15 16]]


Bài tập 2: Thống kê & Vận hành
Yêu cầu:
• Tạo một ma trận 3x3 chứa các số nguyên ngẫu nhiên từ 1
đến 20.
• Tính giá trị trung bình (mean) của toàn bộ ma trận.
• Tìm giá trị lớn nhất (max) của mỗi hàng (sử dụng `axis=1`).

In [ ]:
vector2=np.random.randint(1,21,size=(3, 3))
print(vector2)
mean_value=np.mean(vector2)
print(mean_value)
max_value=np.max(vector2,axis=1)
print(max_value)

[[11  5  7]
 [16 14 11]
 [ 5  2 18]]
9.88888888888889
[11 16 18]


Bài tập 3: Phép nhân Ma trận
Cho 2 ma trận:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])
Tính:
• a) Tích ma trận: `A @ B`
• b) Tích theo từng phần tử: `A * B`

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
C= A@B
print(C)
D=A*B
print(D)

[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


Bài tập 4: Đại số Tuyến tính
Sử dụng ma trận `A` từ Bài tập 3:
Tính:
• a) Ma trận chuyển vị của A (`A.T`).
• b) Ma trận nghịch đảo của A (`np.linalg.inv(A)`).

In [ ]:
E=A.T
print(E)
F=np.linalg.inv(A)
print(F)

[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
